# Generated by Django 2.2.4 on 2019-08-12 13:28

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=18)),
                ('P', models.TextField()),
                ('Status', models.CharField(choices=[('Scheduled', 'Scheduled'), ('Running', 'Running'), ('Complete', 'Complete'), ('Multi-Runs', 'Multi-Runs'), ('Idle', 'Idle')], max_length=10)),
                ('StartDate', models.DateTimeField(null='true')),
                ('EndDate', models.DateTimeField(null='true')),
            ],
        ),
    ]
