# Generated by Django 2.2.4 on 2019-08-13 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taskbrowser', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='priority',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='task',
            name='taskowner',
            field=models.CharField(default='no owner', max_length=30),
        ),
    ]
